name: Testar Projeto Flutter

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Analisar o código
        run: flutter analyze

      - name: Rodar testes
        run: flutter test

