name: Sync main to develop

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/UNICV-TECH/unicv_tech_mvp.git

      - name: Sincronizar develop com main
        run: |
          git fetch origin
          git checkout develop
          git merge origin/main --allow-unrelated-histories --no-edit --strategy-option theirs
          git push origin develop
